### ISSUE TITLE
How to setup an simulation experiment?

### ISSUE THREAD

**Issue by woshidaye** [hrnr/m-explore#10]
How to setup an simulation experiment?

**Comment by hrnr** [comment]
For both packages there are available wiki pages linked in the README of this repository.

Suggestions leading to better documentation are welcome. If you think some parts of the wiki page could be more clear, or you think there is something wrong in the wiki, please feel free to post in this issue or another one.

Also if you want to contribute tutorial for the wiki page or better screenshots etc. I can sponsor that work and update the wiki if you don't have account for the ROS wiki.

For now I'm closing this issue as invalid as the issue does not even specify which package it is referring to. Feel free to reopen if you have some specific suggestions as mentioned above.
