### ISSUE TITLE
Bug in merging_pipeline

### ISSUE THREAD

**Issue by MaxGsomGsom** [hrnr/m-explore#14]
Crash when ``grids_[0] = null``
https://github.com/hrnr/m-explore/blob/717e7f6ea7dfc42cc5a403fff5088f2d50602c6c/map_merge/src/combine_grids/merging_pipeline.cpp#L158-L159
Possible fix
```
  for (auto grid: grids_)
    if (grid) {
        result->info.resolution = grid->info.resolution;
        break;
    }
```

**Comment by hrnr** [comment]
Thanks for reporting this. Actually we need to find a grid, which is a reference frame, in case we have multiple resolutions.

**Comment by hrnr** [comment]
Thanks again for the report. I have fixed this along with some other issues. The crash is fixed and the behaviour when there is no merge possible should be improved.
