### ISSUE TITLE
When giving known positions assertion error occurs

### ISSUE THREAD

**Issue by ccimrie** [hrnr/m-explore#16]
Hi,

If I provide the following the launch file
``` xml
<launch>
  <group ns="/robot1/map_merge">
    <param name="init_pose_x" value="0.068853"/>
    <param name="init_pose_y" value="-0.708363"/>
    <param name="init_pose_z" value="0.035003"/>
    <param name="init_pose_yaw" value="-0.031117"/>
  </group>
  <group ns="/robot2/map_merge">
    <param name="init_pose_x" value="-0.206623"/>
    <param name="init_pose_y" value="1.092293"/>
    <param name="init_pose_z" value="0.034994"/>
    <param name="init_pose_yaw" value="-0.340292"/>
  </group>
    <group ns="map_merge">
      <node pkg="multirobot_map_merge" type="map_merge" respawn="false" name="map_merge" output="screen">
        <param name="robot_map_topic" value="map"/>
        <param name="robot_namespace" value=""/>
        <param name="merged_map_topic" value="map"/>
        <param name="world_frame" value="map"/>
        <param name="known_init_poses" value="true"/>
        <param name="merging_rate" value="0.5"/>
        <param name="discovery_rate" value="0.05"/>
        <param name="estimation_rate" value="0.1"/>
        <param name="estimation_confidence" value="1.0"/>
      </node>
    </group>
</launch>
```

and set known_init_poses to false then it will work fine, but if I set it to true then I get the following assertion error:
![screenshot](https://user-images.githubusercontent.com/6237344/41242276-f3d4a968-6d96-11e8-8cd5-3594af02579d.png)

And I'm not sure what this means.

**Comment by hrnr** [comment]
Thanks for reporting. The bug is fixed in 745ae1e79a8289ca825cce7f7382e3e611073171

Use current master to receive the fix.

**Comment by ccimrie** [comment]
Hi,

Thanks for getting back so quickly!

That's it working, though the merged map produced is a little off. I have 4 robots in a room in Gazebo (they're the 4 black dots in the bottom left room):

![gazebo_setup](https://user-images.githubusercontent.com/6237344/41301645-70454fec-6e60-11e8-8f4d-c87d88ba2e5f.png)

I'm only using concerned with merging three of the robots' maps, and below are there produced maps:

![robot0](https://user-images.githubusercontent.com/6237344/41301756-b9ece2ea-6e60-11e8-857a-6f280852d7d5.png)
![robot1](https://user-images.githubusercontent.com/6237344/41301764-bcaa4202-6e60-11e8-970d-029521746771.png)
![robot2](https://user-images.githubusercontent.com/6237344/41301769-bead8a6e-6e60-11e8-8db3-c785c6f1eab5.png)

Using the XML file:
``` xml
<launch>
  <group ns="/robot0/map_merge">
    <param name="init_pose_x" value="40.003349"/>
    <param name="init_pose_y" value="-20.011330"/>
    <param name="init_pose_z" value="0.180003"/>
    <param name="init_pose_yaw" value="-0.000910"/>
  </group>

  <group ns="/robot1/map_merge">
    <param name="init_pose_x" value="39.964791"/>
    <param name="init_pose_y" value="-22.008312"/>
    <param name="init_pose_z" value="0.180003"/>
    <param name="init_pose_yaw" value="-3.045119"/>
  </group>

  <group ns="/robot2/map_merge">
    <param name="init_pose_x" value="40.005176"/>
    <param name="init_pose_y" value="-22.017528"/>
    <param name="init_pose_z" value="0.180003"/>
    <param name="init_pose_yaw" value="-0.001420"/>
  </group>

    <group ns="map_merge">
      <node pkg="multirobot_map_merge" type="map_merge" respawn="false" name="map_merge" output="screen">
        <param name="robot_map_topic" value="map"/>
        <param name="robot_namespace" value=""/>
        <param name="merged_map_topic" value="map"/>
        <param name="world_frame" value="map"/>
        <param name="known_init_poses" value="true"/>
        <param name="merging_rate" value="0.5"/>
        <param name="discovery_rate" value="0.05"/>
        <param name="estimation_rate" value="0.1"/>
        <param name="estimation_confidence" value="1.0"/>
      </node>
    </group>
</launch>
```
however produces this output:

![map_merge_output](https://user-images.githubusercontent.com/6237344/41301820-da238a5a-6e60-11e8-8591-bfed9c9a1505.png)

Where two of the robots are merged together at the opposite side of the other robot?

(Sorry for potentially too many pictures!)

**Comment by hrnr** [comment]
The initial positions you are giving seems weird. Are you sure they are correct? The merged map clearly contains one map rotated. That would be the map for robot1, since you have put rotation to its `init_pose_yaw`.

Why the headings are not the same? To me the roots seems to be aligned with the coordinate system and they seems to have the same heading.

If you are sure the initial positions are indeed correct, there might be a problem with `map_merge` handling of map origins. You might need to offset the origins manually.

I still need to investigate the issue with map origins, see #15. It would help if you could provide the maps in .yaml+.pgm `map_server` format.

As a workaround just adjust the initial positions you are giving until you get the correct merge. If you let me know what transformation was needed to initial positions to get the correct merge, I can then fix map_merge to do it automatically. I believe we just need to transform the initial positions by the map origins, but I might be wrong.
