### ISSUE TITLE
Release for Melodic

### ISSUE THREAD

**Issue by hrnr** [hrnr/m-explore#17]

**Comment by hrnr** [comment]
waiting for `move_base` to become available in Melodic

**Comment by hrnr** [comment]
`move_base` is in. there are no blockers right now. pending free time.

**Comment by rmerriam** [comment]
I don't find the Melodic version in the ROS system. I cloned and compiled and it works. Will a release be made?

**Comment by rojinphilip** [comment]
> I don't find the Melodic version in the ROS system. I cloned and compiled and it works. Will a release be made?

Hi, How did you compile it? I'm trying it use it for turtle bot [tutorial. ](https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#virtual-slam-by-multiple-turtlebot3s)

Thank you.

**Comment by Timple** [comment]
@hrnr If free time is still an issue, I can do the release if you like.

**Comment by hrnr** [comment]
Release for Melodic is in PR: https://github.com/ros/rosdistro/pull/27878
