### ISSUE TITLE
Hi can you tell me how to set the map_merge.launch

### ISSUE THREAD

**Issue by gaohongfein** [hrnr/m-explore#18]
I don't know how to set this file, and how to set a world frame. The merge map is always not in right position

**Comment by hrnr** [comment]
Hi GaoHF,

I don't know what you mean by "set the map_merge.launch". I have tried my best to explain the setup on the [wiki](http://wiki.ros.org/multirobot_map_merge).

If you think some sections of the wiki could be improved, feel free to propose the changes.

Cheers,
Jiri
