### ISSUE TITLE
About custom the algorithm

### ISSUE THREAD

**Issue by thanhthtran** [hrnr/m-explore#23]
Hi,
Thank you for sharing the frontier exploration algorithm. It works nicely. However, i would like ask that if i want the robot come to the closest frontier near the robot or go to where the map has much frontiers points, where is in your code would i need to change more? would you give me a brief recommendation please?
Thank you

**Comment by hrnr** [comment]
sure, the frontier selected for pursue is selected here:

https://github.com/hrnr/m-explore/blob/745ae1e79a8289ca825cce7f7382e3e611073171/explore/src/explore.cpp#L201-L205

you get a sorted list of frontiers found in the map. It is sorted according to the cost function here:

https://github.com/hrnr/m-explore/blob/745ae1e79a8289ca825cce7f7382e3e611073171/explore/src/frontier_search.cpp#L191-L196

Cheers,
Jiri
