### ISSUE TITLE
Merge multiple maps into one map 

### ISSUE THREAD

**Issue by Chrisch2410** [hrnr/m-explore#35]
Hi, we have a problem merging three maps from thre turtlebots into one, i have in the tf tree the connection between the maps into the map merge, but when i try to visualize in Rviz, the map merge just take the values of one of the maps, and not a map like it should be. First we have problems to get the transform between the maps, we did what it said in some commits that appears in [https://github.com/hrnr/m-explore/pull/30/commits](url) but, the problem continues. the configuration of map_merge.launch is .

`<launch>`
`<group ns="map_merge">`
  `<node pkg="multirobot_map_merge" type="map_merge" respawn="false" name="map_merge" output="screen">`
   ` <param name="robot_map_topic" value="map"/>`
    `<param name="robot_map_updates_topic" value="map_updates"/>`
    `<param name="robot_namespace" value="robot_"/>`
    `<param name="merged_map_topic" value="/map"/>`
   ` <param name="world_frame" value="/map"/>`
    `<param name="known_init_poses" value="false"/>`
    `<param name="merging_rate" value="4.0"/>`
    `<param name="discovery_rate" value="0.05"/>`
    `<param name="estimation_rate" value="0.5"/>`
   ` <param name="publish_rate" value="1.0"/>`
    `<param name="estimation_confidence" value="1.0"/>`
`  </node>`
`</group>`
`</launch>`

Frames tree it's like this.

[frames (23).pdf](https://github.com/hrnr/m-explore/files/3654440/frames.23.pdf)

the map that should be the merge between other maps

![Map merge](https://user-images.githubusercontent.com/41655616/65633315-18992680-dfdc-11e9-888a-19a1bcf92da2.png)

the map 1 is like this 
![map 1](https://user-images.githubusercontent.com/41655616/65633422-5e55ef00-dfdc-11e9-9a53-354b9a0ebf55.png)

the map 2 is like this.

![map2](https://user-images.githubusercontent.com/41655616/65633436-6746c080-dfdc-11e9-80a3-d2bb194aa742.png)

the map 3 is like this.
![map3](https://user-images.githubusercontent.com/41655616/65633441-6dd53800-dfdc-11e9-9e6b-7b3fae8b1b07.png)

the map that should be merge is like this ( visualizing the three maps at the same time).
![all_maps_without_merge](https://user-images.githubusercontent.com/41655616/65633480-80e80800-dfdc-11e9-84d2-6dc9d9b870fa.png)

**Comment by andresjguevara** [comment]
Hola Christian. Pudieron resolver el problema? He visto sus videos de ROS Ignite Academy en youtube (#66 y #67) y pareciera ser que si lograron resolverlo pero nosotros estamos teninedo algunos problemas usando los turtlebots3 en un escenario real (no simulado). Seguimos los pasos que ofrecen en el ROSJect de la academia pero el mapa que se genera no es muy accurate. Habra alguna forma de contactarlo directamente? Muchas gracias!

**Comment by hrnr** [comment]
If you are using mode without providing initial transformations, then you need to each to be a bit larger a to have enough overlap. Otherwise the transformation between the maps can not be estimated.
