### ISSUE TITLE
map_merger subscribes two map topics, but only displaying one

### ISSUE THREAD

**Issue by SYSUHPK** [hrnr/m-explore#36]
@hrnr @yzrobot 
① I use the following **bag(including two robots)** and **a multi-robots-framework** to process and publish two maps, meanwhile I use m-explore to **merge** them online but I just **see three maps with rviz**, **and the merged map is the same as one of original maps**.
② I see some similar issues here 
[https://github.com/hrnr/m-explore/issues/13](url)
but m-explore works well, and I think **the overlap area is big enough**.  It just could not show the merged map with rviz(one of two original maps instead).
③ I also set the estimation confidence to 0.5
**Data set：**
2robots-hospital.bag
**Commands:**
<pre>
roslaunch multirobot_map_merge map_merge.launch
</pre>
**Results：**
robot0(g2o format)：
![2019_11_17_robot0_1](https://user-images.githubusercontent.com/47689665/69030163-bb38b900-0a11-11ea-9f31-a678952d8ec8.png)

robot1(g2o format)：
![2019_11_17_robot1_1](https://user-images.githubusercontent.com/47689665/69030173-becc4000-0a11-11ea-9e67-f622f0b00eab.png)

the merged map using offline tool g2o_viewer:
![2019_11_17_map1](https://user-images.githubusercontent.com/47689665/69030207-d0ade300-0a11-11ea-80f6-30648735ce55.png)

**pgm**
**robot0:**
![robot0_1](https://user-images.githubusercontent.com/47689665/69148451-519ed480-0b0f-11ea-91ab-bb8f62e663b6.png)
**robot1**
![2019_11_18_robot1_1](https://user-images.githubusercontent.com/47689665/69148471-5bc0d300-0b0f-11ea-8d68-4cc5d0d5d8cb.png)
**merged_map**
![2019_11_18_map_1](https://user-images.githubusercontent.com/47689665/69148508-709d6680-0b0f-11ea-99f0-cf7e0ba8093f.png)

Termiante:
![Snipaste_2019-11-18_14-47-35](https://user-images.githubusercontent.com/47689665/69030411-82e5aa80-0a12-11ea-9ee0-060813209f00.png)
![2019_11_18_merge](https://user-images.githubusercontent.com/47689665/69035310-5041af00-0a1e-11ea-8dfc-852202c48b6b.png)

**Topic**
<pre>
robot0/map
robot1/map
</pre>

Question：
1. As the figure shown above, the merged map is the same as one of two(As shown in pgms above), I cannot find out the reason.
2. I find that the status in rviz about the merged map is error(**No transform from world to robot_0/map**), but I can still see the graph. I don‘t know whether it matters.
3. I doubt that maybe there is some problems in data format, but the figure above in terminate shows it works well, so maybe not the data format?

**Comment by hrnr** [comment]
Unfortunately, I can't access any of the attachments. Could you please upload somewhere the two maps in map_server format?

**Comment by SYSUHPK** [comment]
I think I have solved it, thanks a lot.
