### ISSUE TITLE
dims of the result map does not match with the input

### ISSUE THREAD

**Issue by nirandaperera** [hrnr/m-explore#37]
Hi, 

I am using 2 robots that produce 160x160 maps and the initial positions are provided. The resultant map I get is 164x161. Why wouldn't the merged map match with the input maps?  is there a configuration param that could restrict the size of the maps?

**Comment by hrnr** [comment]
Clearly, if robots start with some offset or rotation it is expected that the resulting map will be larger to accommodate both maps.
