### ISSUE TITLE
Some code questions

### ISSUE THREAD

**Issue by Darkproduct** [hrnr/m-explore#38]
Currently, I'm reading my way through the source code to understand how everything is working and adept maybe some parts, but there are parts I don't understand.

1. Why are there 2 `ros::NodeHandle`'s in `class Explore`?

2. How does the `while (ros::ok() && ...)` loop in the constructor of `class Costmap2DClient` work. I would think this blocks everything and I can't see any threads being used. (`explore.cpp` includes `thread` but never uses it?) So can `updateFullMap` ever be called? And even if a loop in the constructor?

3. Is there any reason why you nest your ros callback function in a lambda?
```
costmap_updates_sub_ =
      subscription_nh.subscribe<map_msgs::OccupancyGridUpdate>(
          costmap_updates_topic, 1000,
          [this](const map_msgs::OccupancyGridUpdate::ConstPtr& msg) {
            updatePartialMap(msg);
          });
```
Isn't this much more straigt forward:
```
costmap_updates_sub_ = 
      subscription_nh.subscribe<nav_msgs::OccupancyGrid>(
            costmap_topic, 1000, &Costmap2DClient::updateFullMap, this);
```

**Comment by hrnr** [comment]
1. See http://wiki.ros.org/roscpp/Overview/NodeHandles one is private node handle and the other one is relative nodehandle - as usual you want to use relative node handle for subscribing to topics and private node handle to read params.
2. The loop just waits until tf transfromation from global_frameto robot_base_frame is available then the constructor ends. There is indeed no threading involved while constructing.
3. It is indeed the same. Just a matter of preference/consistency with the other callbacks. If ros would be designed in modern cpp age, it wouldn't have probably all those overloads and would take just std::function.
