### ISSUE TITLE
Pausing and Restarting Exploration

### ISSUE THREAD

**Issue by rmerriam** [hrnr/m-explore#39]
Working with a version built for Melodic and it goes well.

What I need to do is stop the exploration at certain times even when a goal is incomplete. This when another sensor detects something of interest. After the processing of the sensor data I need to restart the exploration. 

Can I do this? Or would changes be needed?

**Comment by blablebli-robots** [comment]
Hello there,

Try calling exploring_timer_.stop() for pausing and exploring_timer_.start() to resume. You may also have to bounce off makePlan(), (e.g. setting a flag) when paused, as there is no need for it to be running during a pause.

**Comment by craigatproperly** [comment]
Old thread, but, was dealing with the same issue. Was considering something like adding an action called explore that could be triggered and cancelled (and configurable to not start exploring automatically).  If something like that was added is that a pull request maintainers would consider merging back; or is there some other approach that should be considered.

**Comment by hrnr** [comment]
Would adding simple services for start and stop be enough for your usecase?

**Comment by rmerriam** [comment]
No longer interested

**Comment by craigatproperly** [comment]
> Would adding simple services for start and stop be enough for your usecase?

We ended up doing that in a fork; do you want PR for that?

**Comment by hrnr** [comment]
yes, that would be welcomed. Thanks.
