### ISSUE TITLE
While just spawned in unknown enviroment, robot cannot start exploration

### ISSUE THREAD

**Issue by artemiialessandrini** [hrnr/m-explore#42]
I use move_base + cartographer + explore setup, but the robot only starts exploring after having some map update manually by move_base/goal ActionClient from RViz.
Without it stopes exploration:

`Exploration stopped.`

Any ideas why it could happen?

**Comment by blablebli-robots** [comment]
Cartographer's maps are tricky. I suggest you figure out first what the cause is. It may be that no frontiers are being found due to the map.

**Comment by hrnr** [comment]
There is unfortunately problem with google cartographer. I suggest waiting until #28 is fixed.
