### ISSUE TITLE
Release for Noetic / ROS2

### ISSUE THREAD

**Issue by benjaminchristie** [hrnr/m-explore#44]
Are there any plans for a Noetic release or a ROS2 release?
Thanks!

**Comment by hrnr** [comment]
Inclusion for noetic is in PR: https://github.com/ros/rosdistro/pull/27879.

I have currently no immediate plans for ROS2 version, that would require a bigger rework. With that said, I'm interested in ROS 2 and I'm welcoming proposals here.

**Comment by WangFengtu1996** [comment]
* Are there any updates about a Noetic release or a ROS2 release ?
