### ISSUE TITLE
multimap merge problem

### ISSUE THREAD

**Issue by Ederwardlu** [hrnr/m-explore#47]
when i set know_init_poses ='false',it just show last robot map under the topic 'map',the 'merge node 'subsciber every 'robot/map',why did it occur? @hrnr

**Comment by hrnr** [comment]
I can't provide much help without details here. It apparently failed to register the maps, which can be caused by multiple reasons. Any suggestions for improving this section are welcome. http://wiki.ros.org/multirobot_map_merge#merging_without_known_initial_positions
