### ISSUE TITLE
Assertion error when merging with four robots' map

### ISSUE THREAD

**Issue by SYSUHPK** [hrnr/m-explore#50]
Hello, when I try to merge the 2d occupancy grid maps with the ros package you provide(That's a nice work!).
It works wll when I publish two robots' maps. But when I try to merge four robots' data with it, I find it reports an error shown as below:
  
![image](https://user-images.githubusercontent.com/47689665/95668984-7085d980-0bad-11eb-8e35-27a31c4a8193.png)

I have tried to solve it in many ways but failed. It seems that the Assertion error should not have happened for roi.size() must equals to warped_grid.size()
I can't understand why it throws this error. Do you have any idea about it? @hrnr

**Comment by hrnr** [comment]
Thanks for the report, looks indeed like a bug.

Could you send me the maps you are trying to merge in map_server format, so
I could reproduce it?


Cheers,
Jiri

**Comment by SYSUHPK** [comment]
Sorry to reply so late, I have been dealing with some other things these months. Well, the problem is avoided by skipping some dataset inputs, without fixing it. I need some time to reproduce it.

**Comment by SYSUHPK** [comment]
Sorry to reply so late, I have been dealing with some other things these months. Well, the problem is avoided by skipping some dataset inputs, without fixing it. I need some time to reproduce it.
