### ISSUE TITLE
issue when exploring the large open area

### ISSUE THREAD

**Issue by sihanh** [hrnr/m-explore#52]
when I tried to use explore_lite in a large open area, the robot sometimes stuck in place and never moved again. There are available frontiers that can be visualized viaMarkerArray with rviz but the exlor_lite doesn't send any of them to move_base goal action. Also when I manually set the goal point, the robot can move toward the point but shortly after will be drag back to the stuck location where explore_lite sent. This also happens when robot spawns in a position where facing walls and no frontier explored.

![error](https://user-images.githubusercontent.com/48574298/104166381-b1ec8600-5435-11eb-9007-10a8c1b8bcb9.png)

the above image shows the robot stuck in an open area. But shortly after the frontier will become red (assume as goal in blacklist), then it will become normal again. There is a goal sending to move base but the goal locates at same spot where robot stuck.
![erro2](https://user-images.githubusercontent.com/48574298/104167035-a3eb3500-5436-11eb-85ee-5649c8b9b44f.png)
![error3](https://user-images.githubusercontent.com/48574298/104167045-a8175280-5436-11eb-8bfd-65c2eeb4af94.png)

**Comment by hrnr** [comment]
Could you share a map where this happens? Ideally, a reproducer in a simulated environment would be very helpful.

**Comment by sihanh** [comment]
> Could you share a map where this happens? Ideally, a reproducer in a simulated environment would be very helpful.

added pictures describing the dilemma, the goal can only be sent effectively when frontiers are red
