### ISSUE TITLE
Waiting to connect to move_base server

### ISSUE THREAD

**Issue by CycleMark** [hrnr/m-explore#77]
Hi,

This might be a topic mapping issue. At the moment when I bring up the out of the box explore.launch it's sat with:
[ INFO] [1678278240.706816797]: Waiting to connect to move_base server

However there is a move_base server:

![image](https://user-images.githubusercontent.com/27418725/223717303-6da35ed4-ff2c-4208-a9a9-34b1fcfcd125.png)

Any idea why this is happening?

Thanks

Mark

**Comment by CycleMark** [comment]
Resolved :)

**Comment by ismaeelbashir03** [comment]
Can you say what solved the issue? I am having the same thing happen to me.
